import { business } from "./business.js";

const R = business.region;

const sharedFaqs = [
  {
    q: "Is American General Contractor licensed and insured?",
    a: `Yes. American General Contractor LLC is a registered New Jersey Home Improvement Contractor (${business.license}) and is fully insured.`,
  },
  {
    q: "How do I get an estimate?",
    a: `Use the estimate request form on this site or call ${business.phone.display}. Tell us about the project, add photos if you have them, and a member of our team will contact you about the next step. Estimates are free.`,
  },
];

export const services = [
  {
    slug: "kitchen-remodeling",
    name: "Kitchen Remodeling",
    summary: "Layouts, cabinetry, counters, tile and lighting brought together into a kitchen that works the way you cook and live.",
    icon: "kitchen",
    image: "kitchen",
    metaTitle: `Kitchen Remodeling in ${R}`,
    metaDescription: `Kitchen remodeling for ${R} homeowners: cabinets, countertops, tile, flooring and layout changes. Fully insured, ${business.license}. Request a free estimate.`,
    h1: `Kitchen remodeling in ${R}`,
    intro: [
      "The kitchen is usually the hardest-working room in the house, and the one where a remodel changes daily life the most. We handle the project from the first measurements through the final walkthrough, so you are not coordinating separate trades on your own.",
      "Some kitchens need new cabinets, counters and flooring in the existing footprint. Others need walls moved and the whole layout rethought. We bring the same attention to quality and communication to both.",
    ],
    includesTitle: "What a kitchen project can include",
    includes: [
      "Cabinet installation and replacement",
      "Countertops and backsplash tile",
      "Kitchen flooring",
      "Layout changes and wall removal",
      "Islands and peninsulas",
      "Lighting and fixture updates",
      "Trim, paint and finish carpentry",
    ],
    faqs: [
      {
        q: "Can I stay in my home during a kitchen remodel?",
        a: "Most homeowners do. Before work starts we talk through the schedule and what parts of the home will be affected, so you can plan around it.",
      },
      ...sharedFaqs,
    ],
    related: ["flooring", "general-remodeling", "bathroom-remodeling"],
    estimateType: "Kitchen Remodeling",
  },
  {
    slug: "bathroom-remodeling",
    name: "Bathroom Remodeling",
    summary: "Full renovations, shower upgrades, glass doors, vanities, tile and fixtures, finished with care for the details.",
    icon: "bath",
    image: "bathroom",
    metaTitle: `Bathroom Remodeling in ${R}`,
    metaDescription: `Bathroom renovations, shower upgrades, glass shower doors, vanities, tile and flooring for ${R} homes. Fully insured, ${business.license}. Free estimates.`,
    h1: `Bathroom remodeling in ${R}`,
    intro: [
      "Bathrooms pack a lot of detail into a small space: waterproofing, tile layout, plumbing fixtures, ventilation and glass all have to come together cleanly. That is where careful workmanship shows.",
      "We take on full bathroom renovations as well as focused upgrades such as a new shower, a glass door installation or a vanity replacement.",
    ],
    includesTitle: "What a bathroom project can include",
    includes: [
      "Full bathroom renovations",
      "Shower upgrades and tub-to-shower conversions",
      "Shower and glass door installation",
      "Vanities and countertops",
      "Fixtures and hardware",
      "Wall and floor tile",
      "Bathroom flooring",
    ],
    faqs: [
      {
        q: "Do you install glass shower doors on their own?",
        a: "Yes. Shower and glass door installation can be part of a full renovation or a standalone project. Choose “Shower / Glass Door Installation” on the estimate form.",
      },
      ...sharedFaqs,
    ],
    related: ["flooring", "kitchen-remodeling", "general-remodeling"],
    estimateType: "Bathroom Remodeling",
  },
  {
    slug: "additions",
    name: "Home Additions",
    summary: "More room where you need it, built to look and feel like it was always part of the house.",
    icon: "addition",
    image: "addition",
    metaTitle: `Home Additions in ${R}`,
    metaDescription: `Home additions for ${R} homeowners who need more space: room additions, expansions and large-scale renovations. Fully insured, ${business.license}.`,
    h1: `Home additions in ${R}`,
    intro: [
      "When you like where you live but have outgrown the house, an addition is often the better answer than moving. It is also one of the larger projects a homeowner takes on, which makes planning and communication as important as the construction itself.",
      "Our experience runs from everyday homes to million-dollar properties, and an addition gets the same standard either way: it should tie into the existing structure, rooflines and finishes so it does not read as an afterthought.",
    ],
    includesTitle: "Addition projects we take on",
    includes: [
      "Room additions and bump-outs",
      "Primary suite additions",
      "Family room and living space expansions",
      "Tying new framing into the existing structure",
      "Matching exterior and interior finishes",
      "Windows, doors and flooring for the new space",
    ],
    faqs: [
      {
        q: "Will an addition need permits?",
        a: "Additions in New Jersey generally require permits and inspections, and the specifics vary by municipality. We will talk through what your project is likely to need when we discuss your estimate.",
      },
      ...sharedFaqs,
    ],
    related: ["general-remodeling", "windows-doors", "flooring"],
    estimateType: "Addition",
  },
  {
    slug: "decks-outdoor-living",
    name: "Decks & Outdoor Living",
    summary: "Decks, railings, covered areas and outdoor spaces built for South Jersey summers and everything in between.",
    icon: "deck",
    image: "deck",
    metaTitle: `Deck Contractor & Outdoor Living in ${R}`,
    metaDescription: `Deck building, railings, covered outdoor areas and outdoor living improvements across ${R}. Fully insured, ${business.license}. Request a free estimate.`,
    h1: `Decks and outdoor living in ${R}`,
    intro: [
      "A well-built deck extends the house. It gives you a place to eat, gather and get outside for most of the year, and it has to stand up to sun, salt air and winter weather.",
      "We build new decks, replace aging ones and put together complete outdoor living areas with railings, covered sections and pergolas.",
    ],
    includesTitle: "Outdoor projects we take on",
    includes: [
      "New deck construction",
      "Deck replacement and resurfacing",
      "Railings and stairs",
      "Covered outdoor areas",
      "Pergolas",
      "Other exterior living improvements",
    ],
    faqs: [
      {
        q: "Do decks require a permit in New Jersey?",
        a: "In most New Jersey municipalities they do, though requirements vary by town and by the size and height of the deck. We will go over what applies to your project during the estimate conversation.",
      },
      ...sharedFaqs,
    ],
    related: ["pergolas", "windows-doors", "general-remodeling"],
    estimateType: "Deck",
  },
  {
    slug: "pergolas",
    name: "Pergola Installation",
    summary: "Shade, structure and a defined place to gather. One of our most requested outdoor projects.",
    icon: "pergola",
    image: "pergola",
    metaTitle: `Pergola Installation in ${R}`,
    metaDescription: `Pergola installation for ${R} patios, decks and backyards. Shade and structure built to last. Fully insured, ${business.license}. Request a free estimate.`,
    h1: `Pergola installation in ${R}`,
    intro: [
      "A pergola turns an open patio or deck into a defined outdoor room. It adds shade, frames the space and gives you somewhere to hang lighting or grow climbing plants.",
      "Pergolas are among the projects homeowners ask us about most. We install them over patios and decks and as freestanding backyard structures, sized and positioned for how you plan to use the space.",
    ],
    includesTitle: "Pergola options",
    includes: [
      "Freestanding backyard pergolas",
      "Pergolas attached to the house",
      "Pergolas over decks and patios",
      "Sizing and placement for shade and use",
      "Footings, posts and structural anchoring",
      "Pairing with a new deck or outdoor living project",
    ],
    faqs: [
      {
        q: "What should I send to get a pergola estimate?",
        a: "Approximate measurements of the area, a few photos of the space, and any inspiration photos showing the style you like. The estimate form has a place to upload all three.",
      },
      ...sharedFaqs,
    ],
    related: ["decks-outdoor-living", "general-remodeling", "windows-doors"],
    estimateType: "Pergola / Outdoor Living",
  },
  {
    slug: "windows-doors",
    name: "Windows & Doors",
    summary: "Window replacement and exterior, entry and patio door installation, fitted and sealed properly.",
    icon: "window",
    image: "windows",
    metaTitle: `Window & Door Installation in ${R}`,
    metaDescription: `Window installation and replacement plus entry, exterior and patio door installation for ${R} homes. Fully insured, ${business.license}. Free estimates.`,
    h1: `Window and door installation in ${R}`,
    intro: [
      "New windows and doors change how a house looks from the street and how comfortable it feels inside. The product matters, but the installation matters more: a good window installed poorly still leaks air and water.",
      "We install and replace windows and exterior doors with attention to fit, flashing, sealing and trim, inside and out.",
    ],
    includesTitle: "Window and door work",
    includes: [
      "Window installation and replacement",
      "Entry door installation",
      "Exterior door replacement",
      "Patio and sliding doors",
      "Interior and exterior trim",
      "Openings for additions and remodels",
    ],
    faqs: [
      {
        q: "Do you install interior shower glass doors under this service?",
        a: "Shower and glass door installation is handled as part of our bathroom remodeling work. This page covers exterior windows and doors.",
      },
      ...sharedFaqs,
    ],
    related: ["additions", "general-remodeling", "bathroom-remodeling"],
    estimateType: "Windows",
  },
  {
    slug: "flooring",
    name: "Flooring",
    summary: "New floors installed over properly prepared subfloors, in a single room or through the whole house.",
    icon: "floor",
    image: "flooring",
    metaTitle: `Flooring Contractor in ${R}`,
    metaDescription: `Flooring installation for ${R} homes and businesses: kitchens, bathrooms, living areas and whole-home projects. Fully insured, ${business.license}.`,
    h1: `Flooring installation in ${R}`,
    intro: [
      "Floors take more wear than any other surface in a home. How long they last has as much to do with preparation and installation as with the material you choose.",
      "We install flooring as a standalone project and as part of kitchen, bathroom and whole-home remodels.",
    ],
    includesTitle: "Flooring work",
    includes: [
      "Flooring installation and replacement",
      "Kitchen and bathroom floors",
      "Tile flooring",
      "Subfloor preparation and repair",
      "Transitions, baseboard and trim",
      "Whole-home flooring projects",
    ],
    faqs: [...sharedFaqs],
    related: ["kitchen-remodeling", "bathroom-remodeling", "general-remodeling"],
    estimateType: "Flooring",
  },
  {
    slug: "general-remodeling",
    name: "General Remodeling",
    summary: "Whole-home renovations and multi-room projects managed by one contractor from start to finish.",
    icon: "remodel",
    image: "remodel",
    metaTitle: `Home Remodeling Contractor in ${R}`,
    metaDescription: `General and whole-home remodeling in ${R}, from focused improvements to large-scale renovations. Fully insured, ${business.license}. Request a free estimate.`,
    h1: `Home remodeling in ${R}`,
    intro: [
      "Many projects do not fit neatly into one category. A renovation might touch the kitchen, two bathrooms, the flooring and half the windows. Having one contractor responsible for all of it keeps the schedule, the quality and the communication consistent.",
      "From focused home improvements to large-scale renovations, American General Contractor brings the same attention to quality, communication and craftsmanship to every project. That includes experience working on million-dollar homes.",
    ],
    includesTitle: "Remodeling projects we take on",
    includes: [
      "Whole-home renovations",
      "Multi-room remodels",
      "Interior reconfiguration",
      "Finish carpentry and trim",
      "Drywall and paint as part of a remodel",
      "Coordinating every phase under one contractor",
    ],
    faqs: [
      {
        q: "Do you take on both smaller and larger projects?",
        a: "Yes. Our work ranges from focused home improvements to substantial renovations. Tell us about yours and we will let you know how we can help.",
      },
      ...sharedFaqs,
    ],
    related: ["kitchen-remodeling", "additions", "flooring"],
    estimateType: "General Remodeling",
  },
  {
    slug: "commercial",
    name: "Commercial Construction",
    summary: "Build-outs, renovations and improvements for South Jersey businesses and commercial properties.",
    icon: "commercial",
    image: "commercial",
    secondary: true,
    metaTitle: `Commercial Construction in ${R}`,
    metaDescription: `Commercial construction and renovation for ${R} businesses and property owners. Fully insured, ${business.license}. Tell us about your project.`,
    h1: `Commercial construction in ${R}`,
    intro: [
      "Alongside our residential work, we take on commercial construction and renovation projects for South Jersey businesses and property owners.",
      "Commercial projects come with their own pressures: schedules tied to opening dates, tenants and customers to work around. The same clear communication and workmanship we bring to homes applies here.",
    ],
    includesTitle: "Commercial work",
    includes: [
      "Interior build-outs and renovations",
      "Storefront and entry improvements",
      "Flooring, windows and doors",
      "Office and retail remodeling",
      "Improvements for commercial property owners",
    ],
    faqs: [...sharedFaqs],
    related: ["general-remodeling", "flooring", "windows-doors"],
    estimateType: "Commercial",
  },
];

export const primaryServices = services.filter((s) => !s.secondary);
export const getService = (slug) => services.find((s) => s.slug === slug);
